name: publish to nuget
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install dotnet tool
        run: dotnet tool update -g dotnetCampus.TagToVersion
      - name: Set tag to version  
        run: dotnet TagToVersion -t ${{ github.ref }}

      - name: Build
        run: dotnet build -c Release
      - name: Generate NuGet package
        run: dotnet pack -c Release --no-build -o ./bin/Release/
      - name: Publish to NuGet
        run: dotnet nuget push ./bin/Release/*.nupkg --api-key ${{ secrets.NUGETKEY }} --source "https://api.nuget.org/v3/index.json"
